### PR TITLE
Update readme

### LINKED ISSUE #3: Update README.md with proper installation instructions
#### I propose following changes to the README.md of the project
- The README.md should have the ```npm install``` instruction for people who are setting up the project for the first time.
- There should be a demo gif or an image of the web app in action.

### PR DESCRIPTION
**Pull request by omkar342**
resolve #3

### CODE REVIEW

**Comment by omkar342** [comment]
@PranavTrip Please review the updates made by me & suggest me changes if needed.

**Comment by PranavTrip** [comment]
Nice work @omkar342 loved it.

**Comment by omkar342** [comment]
Thank you so much @PranavTrip.

**Comment by omkar342** [comment]
Hey @PranavTrip, I will be really thankful if you can add the Hactoberfest-accept label to this PR.

**Pull request merged**
