### PR TITLE
Few minor changes

### PR DESCRIPTION
**Pull request by SyedFasiuddin**

### CODE REVIEW

**Comment by SyedFasiuddin** [comment]
I have just made a few minor changes and I would like to do some more changes like make it mobile responsive and not use bootstrap (just use plane css), I'll be working on it now and will make another pull request in few days

**Comment by PranavTrip** [comment]
> I have just made a few minor changes and I would like to do some more changes like make it mobile responsive and not use bootstrap (just use plane css), I'll be working on it now and will make another pull request in few days

There is an issue regarding the responsiveness of the website and it is already assigned to someone else. Sorry, but you can find another issue, then mention it and I shall assign that to you.

**Comment by PranavTrip** [comment]
> I have just made a few minor changes and I would like to do some more changes like make it mobile responsive and not use bootstrap (just use plane css), I'll be working on it now and will make another pull request in few days

Also, please make a pull request in the features branch not in the master branch so kindly close this PR and create a new PR in the features branch

**Comment by SyedFasiuddin** [comment]
Ok so I have made these commits on the main branch of my fork of the project how do I transfer those commits to the features branch?

**Pull request closed without merging**
